### PR TITLE
macOS issues, added warnings, resolved warnings

### PR DESCRIPTION
**Pull request by nrbrook**
- Added some warnings
- Restructured warning flag variables to set common variables for all compilers, and documented shared flags
- Suppressed some warnings
- Resolved issues on macOS
- Resolved warnings during compilation

### CODE REVIEW

**Comment by rben-dev** [comment]
Hi @nrbrook,

Thanks for this PR! (and sorry for the late answer :-)). I understand that your main platform is Mac OS (and thanks for all the patches for it!): have you tested all these modifications on other platforms as well?
One of the concerns is the portability of the `unsigned long` for `PRIx32` (i.e. not triggering issues on embedded platforms and so on).

I will check these commits to ensure that there is no regression on other platforms, and might come back to discuss some modifications.

Anyways thanks for your help on improving the Makefiles and libecc compilation!

Regards,

**Comment by rben-dev** [comment]
image

For your information, under Linux `clang` and `gcc` I have a `-Wformat` warning as attached. We would ideally aim at no warning / errors on all the platforms where libecc is tested.

Regards,

**Comment by rben-dev** [comment]
I have created a new branch https://github.com/libecc/libecc/tree/merge_PR where I am fixing some elements associated to `-Wformat` and strict `__attribute__((format))` (rightly) introduced on various platforms, based on your PR.
The most notable thing here is the usage of `<inttypes.h>` when `STD_LIB` is used as the header properly defines `PRI*` macros, and when no  `STD_LIB` is used a better definition of these macros.
Anyways, this is a work in progress, and I am testing all the various cross-compilation platforms to check if everything is OK before merging.
Do not hesitate to comment this if necessary!

Regards,

**Comment by nrbrook** [comment]
Ok thanks. I tested with Xcode 14.3 and arm-none-eabi-gcc 10.3-2021.07

**Comment by rben-dev** [comment]
Hi,

The integration should be OK and tested in CI on the https://github.com/libecc/libecc/tree/merge_PR branch: as I do not have a Mac OS with Xcode, can you please confirm that the compilation is still OK from this branch on you side (also with `PEDANTIC=1`?). If so, I will merge with the `master` branch!

Thanks in advance,
Regards,

**Comment by rben-dev** [comment]
I finally tested the Mac OS compilation and merged the branch (sorry to have modified your original PR as the new commits resolve many conflicts and compilation issues).

Anyways, do not hesitate to open an issue or another PR if you catch problems on your platforms you use!

Regards,

**Comment by nrbrook** [comment]
Thanks, and sorry I didn't get time to test myself.

**Pull request merged**
